### ISSUE TITLE
Option to remove icon?

### ISSUE THREAD

**Issue by notuntoward** [0x7b1/logseq-plugin-automatic-url-title#1]
Hi, this plugin works very well (*).  Thanks.  

I'd like it even more if it had an option to disable the display the icons next to the link.  For me, they interrupt the reading flow, especially when I later edit the article text and the icon is still tere.  Here's an example:

![image](https://user-images.githubusercontent.com/3851891/179045201-c470d039-6862-4e59-8c80-3ad3aaf30508.png)

(*) The only place I've found so far where it fails is google news: https://news.google.com/topstories?hl=en-US&gl=US&ceid=US:en

**Comment by 0x7b1** [comment]
Hey! Thanks for trying it out and finding a case where the title fetching doesn't work. Seems like I'd have to workaround some cases.
If you want to remove the icon then just override the variable on your `logseq/custom.css` file. Just like 
```
:root {
  --favicons: none;
}
```
