### ISSUE TITLE
options to link in orgmode?

### ISSUE THREAD

**Issue by rdrd0023** [0x7b1/logseq-plugin-automatic-url-title#2]
Hi,
I know this is not intended, but is it possible for you to add the same for org files? The syntax for org is 
`[[LINK][DESCRIPTION]]` or `[[LINK]]`.

**Comment by 0x7b1** [comment]
Hey! Thanks for bringing it up. There's a work in progress to support org format https://github.com/0x7b1/logseq-plugin-automatic-url-title/tree/org-format
Hope it will be ready on the weekend :)
